FROM centos:centos7
MAINTAINER Chuyqa


RUN yum update -y && yum clean all
RUN yum install epel-release -y
RUN yum install python-pip java-1.8.0-openjdk -y


# Maven 3.0.5 
RUN mkdir -p /opt/apache-maven-3.0.5
WORKDIR /opt/apache-maven-3.0.5
RUN wget https://archive.apache.org/dist/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz
RUN tar xvfz apache-maven-3.0.5-bin.tar.gz
RUM rm -f /opt/apache-maven-3.0.5/apache-maven-3.0.5-bin.tar.gz

ENV JAVA_HOME /usr/java/default
ENV M2_HOME /opt/apache-maven-3.0.5
ENV PATH:$JAVA_HOME:$M2_HOME/bin


# Nodejs

# Custom scripts
ADD ./scripts /opt/scripts

# Other
RUN echo 'alias wtf=history | grep ' >> /etc/bashrc
RUN echo 'alias mci=mvn clean install -DskipTests' >> /etc/bashrc
