FROM alpine:3.2

# Additional repositories
RUN repositories="\
  http://dl-4.alpinelinux.org/alpine/v3.2/main/\
  @edge http://nl.alpinelinux.org/alpine/edge/main/\
  @community http://nl.alpinelinux.org/alpine/edge/community/" \
  && echo -e $repositories | sed -e 's/\/\s/\/\n/g' > /etc/apk/repositories

# Install required packages
RUN packages=' \
    bash \
    vim \
    git \
    tar \
    curl \
    wget \
    make \
    unrar \
  ' \
  set -x \
  && apk --update add $packages \
  && rm -rf /var/cache/apk/*

WORKDIR /opt/ 
RUN git clone https://github.com/mcrapet/plowshare
RUN cd plowshare && make install
RUN plowmod --install

ADD ./scripts /opt/scripts
RUN ln -s /opt/scripts/Unrar /usr/bin/Unrar


CMD ["sh"]
