FROM centos:centos7
MAINTAINER Chuyqa


RUN yum update -y && yum clean all
RUN yum -y install epel-release git pip vim wget
RUN yum -y install ansible --enablerepo=epel

# Ansible
ADD files/ansible.cfg /root/.ansible.cfg

#Install JAVA 
RUN wget --no-check-certificate --no-cookies --header "Cookie:oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm -O jdk-8u60-linux-x64.rpm
RUN rpm -Uvh jdk-8u60-linux-x64.rpm
ENV JAVA_HOME /usr/java/default/


# SSH key
RUN ssh-keygen -f /root/.ssh/id_rsa -t rsa -N ''
RUN cat /root/.ssh/id_rsa.pub > /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys


